name: Upload Python Package

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}/${{ matrix.arch || '*' }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-latest
            arch: x86_64
          - os: macos-latest
            arch: arm64
          - os: ubuntu-22.04
            arch: '*'  # unused
          - os: windows-latest
            arch: '*'  # unused

    steps:
      - uses: actions/checkout@v3

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.23.1
        env:
          CIBW_ARCHS_MACOS: ${{ matrix.arch }}

      - name: List wheels
        run: ls -l ./wheelhouse

      - uses: actions/upload-artifact@v4
        with:
          name: artifact-${{ matrix.os }}-${{ matrix.arch }}
          path: ./wheelhouse/*.whl

  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Build sdist
        run: pipx run build --sdist

      - uses: actions/upload-artifact@v4
        with:
          name: artifact-${{ matrix.os }}-${{ matrix.arch }}
          path: dist/*.tar.gz

  PyPI:
    name: Upload to PyPI

    needs: [build_wheels, build_sdist]
    runs-on: ubuntu-22.04
    permissions:
      id-token: write

    steps:
    - uses: actions/download-artifact@v4
      with:
        name: artifact*
        path: dist
        merge-multiple: true
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@release/v1
