# This tries to build packages, and tests the packages.
# It runs on every push to branches following the pattern v*.*.*.
# It makes sure that everything will run when the version is released.

name: Test Build

on:
  workflow_dispatch:
  push:
    branches:
      - v*.*.*
      - build-*

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}/${{ matrix.arch || '*' }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-latest
            arch: x86_64
          - os: macos-latest
            arch: arm64
          - os: ubuntu-latest
            arch: '*'  # unused
          - os: windows-latest
            arch: '*'  # unused

    steps:
      - uses: actions/checkout@v3

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.23.2
        env:
          CIBW_ARCHS_MACOS: ${{ matrix.arch }}

  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build sdist
        run: pipx run build --sdist
